name: on-block all use case
on:
  workflow_dispatch:
<<<<<<< HEAD
jobs:
  on-block:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: run the python file
        run: python3 ./.github/workflows/on-block.py
=======
  input:
    environment:
      description: 'Name of the use case'
      required: true
      type: string
    aws-region:
      description: 'AWS region
      required: true
      type: choice
      options:
        - us-east-1
        - us-west-2
    
    
jobs:
on-block-all-use-case:
  runs-on: ubuntu-latest
  steps:
    -name: on-block all use case
      run: |
        echo "on-block all use case"
    -name: install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    -name: run the code
      run: python sample.py
>>>>>>> 342d1d5a0b870d32b5e46a872493be516e75a89d
