name: on-block all use case
on:
  workflow_dispatch:
jobs:
on-block-all-use-case:
  runs-on: ubuntu-latest
  steps:
    -name: on-block all use case
      run: |
        echo "on-block all use case"
    -name: install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    -name: run the code
      run: python sample.py